// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgxcmiqaonfmbonavyln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1neGNtaXFhb25mbWJvbmF2eWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODIxMjUsImV4cCI6MjA1OTg1ODEyNX0.vrhaqXwwD6ypMaY8vxGZ9no7gey0ciV-dtVpdfrl8mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);